import org.apache.log4j.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    static Logger log = Logger.getLogger(App.class.getName());

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        log.trace("Trace Message!");
        log.debug("Debug Message!");
        log.info("Info Message!");
        log.warn("Warn Message!");
        log.error("Error Message!");
        log.fatal("Fatal Message!");
    }
}
